/**
 * Compiles src/**\/*.jsx -> assets/**\/*.js with the React preset.
 *
 * The site is plain static HTML: each page loads React from a CDN and then its own
 * compiled bundle. JSX is precompiled here so the browser never has to ship or run
 * @babel/standalone (~3.1 MB) on every page load.
 *
 * Usage:  node build.mjs      (or: npm run build)
 *
 * No npm install required. The compiler is resolved in this order:
 *   1. node_modules/@babel/standalone  (if you ran `npm install`)
 *   2. .build-cache/babel.min.js       (downloaded once, gitignored)
 */
import { readdir, readFile, writeFile, mkdir, stat } from 'node:fs/promises';
import { dirname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const ROOT = dirname(fileURLToPath(import.meta.url));
const SRC = join(ROOT, 'src');
const OUT = join(ROOT, 'assets');
const CACHE_DIR = join(ROOT, '.build-cache');
// .cjs so Node treats it as CommonJS despite package.json "type": "module".
const CACHE_FILE = join(CACHE_DIR, 'babel.min.cjs');
const BABEL_URL = 'https://unpkg.com/@babel/standalone@7.29.0/babel.min.js';

async function loadBabel() {
  try {
    return require('@babel/standalone');
  } catch { /* fall through to the cached download */ }

  try {
    await stat(CACHE_FILE);
  } catch {
    console.log(`Fetching the JSX compiler once -> ${relative(ROOT, CACHE_FILE)}`);
    const res = await fetch(BABEL_URL);
    if (!res.ok) throw new Error(`Could not download Babel: HTTP ${res.status}`);
    await mkdir(CACHE_DIR, { recursive: true });
    await writeFile(CACHE_FILE, Buffer.from(await res.arrayBuffer()));
  }
  return require(CACHE_FILE);
}

async function* walk(dir) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name);
    if (entry.isDirectory()) yield* walk(p);
    else if (entry.name.endsWith('.jsx')) yield p;
  }
}

try {
  await stat(SRC);
} catch {
  console.error(`No src/ directory at ${SRC}`);
  process.exit(1);
}

const Babel = await loadBabel();

let count = 0;
for await (const file of walk(SRC)) {
  const rel = relative(SRC, file).replace(/\.jsx$/, '.js');
  const dest = join(OUT, rel);
  const code = await readFile(file, 'utf8');

  let compiled;
  try {
    compiled = Babel.transform(code, { presets: ['react'], filename: file }).code;
  } catch (err) {
    console.error(`FAILED ${rel}: ${err.message}`);
    process.exitCode = 1;
    continue;
  }

  await mkdir(dirname(dest), { recursive: true });
  const srcRel = rel.split(sep).join('/') + 'x';
  await writeFile(dest, `// Generated by build.mjs from src/${srcRel} — do not edit.\n${compiled}\n`, 'utf8');
  console.log(`  ${rel.split(sep).join('/').padEnd(36)} ${compiled.length} bytes`);
  count++;
}

console.log(`\nCompiled ${count} file(s) to assets/.`);
